name: Workflow Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # 自动部署GitPage
  gitpage:
    runs-on: ubuntu-latest
    steps:
    # 拉取代码
    - name: Checkout
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0

    # 设置Node.js环境
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '19'
        cache: 'npm'
    
    # 安装依赖
    - name: Install Dependencies
      run: npm ci
      
    # 编译出静态页面
    - name: Build
      run: npm run build
      env:
        NODE_OPTIONS: --max-old-space-size=8192
        BASE_URL: /TabooLib-guide/
        NODE_ENV: production